export const languages = ['pl', 'en', 'hi'] as const;
export type Lang = (typeof languages)[number];
export type Content = { locale:string; name:string; nav:{menu:string; story:string; visit:string}; order:string; call:string; language:string; skip:string; hero:string; lead:string; now:string; menuTitle:string; menuLead:string; menuLink:string; storyTitle:string; storyText:string; visitTitle:string; visitLead:string; directions:string; addressLabel:string; hoursLabel:string; hours:string; footer:string; menuPageTitle:string; menuPageLead:string; visitPageTitle:string; visitPageLead:string; selected:string };
export const copy: Record<Lang, Content> = {
  pl:{locale:'pl_PL',name:'Indian Curry Włochy',nav:{menu:'Menu',story:'O nas',visit:'Kontakt'},order:'Zamów online',call:'Zadzwoń',language:'Wybierz język',skip:'Przejdź do treści',hero:'Indie na talerzu. Włochy po sąsiedzku.',lead:'Aromatyczne curry, ogień z tandoora i dania przygotowane tak ostro, jak lubisz.',now:'Otwarte codziennie · 11:00–22:00',menuTitle:'Zacznij od <em>czegoś pysznego.</em>',menuLead:'Kremowe, pikantne, wegetariańskie — znajdź swój ulubiony smak.',menuLink:'Zobacz pełne menu',storyTitle:'Smak, który robi <em>różnicę.</em>',storyText:'Nie skracamy drogi do dobrego curry. Przyprawy, tandoor i czas tworzą dania, do których chce się wracać.',visitTitle:'Wpadnij po <em>dobry wieczór.</em>',visitLead:'Na miejscu, na wynos lub z dostawą. Znajdziesz nas przy Równoległej 2 w Warszawie.',directions:'Otwórz trasę',addressLabel:'ADRES',hoursLabel:'GODZINY',hours:'Codziennie · 11:00–22:00',footer:'Kuchnia indyjska w Warszawie Włochy',menuPageTitle:'Co dziś <em>zamawiasz?</em>',menuPageLead:'Kilka pewniaków na początek. Pełna karta czeka w systemie zamówień.',visitPageTitle:'Dobre curry jest <em>blisko.</em>',visitPageLead:'Przyjdź na lunch, kolację albo odbierz zamówienie po drodze do domu.',selected:'Polecamy'},
  en:{locale:'en_GB',name:'Indian Curry Włochy',nav:{menu:'Menu',story:'Our kitchen',visit:'Visit'},order:'Order online',call:'Call us',language:'Choose language',skip:'Skip to content',hero:'India on your plate. Włochy next door.',lead:'Fragrant curry, tandoor fire and food made as mild or as fiery as you like.',now:'Open daily · 11:00–22:00',menuTitle:'Start with <em>something delicious.</em>',menuLead:'Creamy, spicy, vegetarian — find the flavour that is yours.',menuLink:'See full menu',storyTitle:'Flavour that makes <em>a difference.</em>',storyText:'There is no shortcut to great curry. Spices, tandoor and time create dishes worth returning for.',visitTitle:'Come by for <em>a good evening.</em>',visitLead:'Dine in, takeaway or delivery. Find us on Równoległa 2 in Warsaw.',directions:'Get directions',addressLabel:'ADDRESS',hoursLabel:'HOURS',hours:'Every day · 11:00–22:00',footer:'Indian cooking in Warsaw Włochy',menuPageTitle:'What are you <em>ordering today?</em>',menuPageLead:'A few favourites to begin with. The full menu is in our ordering system.',visitPageTitle:'Great curry is <em>close by.</em>',visitPageLead:'Join us for lunch or dinner, or collect an order on your way home.',selected:'Our favourites'},
  hi:{locale:'hi_IN',name:'इंडियन करी व्लोही',nav:{menu:'मेन्यू',story:'हमारी रसोई',visit:'यहाँ आएँ'},order:'ऑनलाइन ऑर्डर करें',call:'फ़ोन करें',language:'भाषा चुनें',skip:'मुख्य सामग्री पर जाएँ',hero:'थाली में भारत। व्लोही आपके पास।',lead:'सुगंधित करी, तंदूर की आँच और आपकी पसंद के अनुसार तीखापन।',now:'हर दिन खुला · 11:00–22:00',menuTitle:'शुरू करें <em>कुछ स्वादिष्ट से।</em>',menuLead:'क्रीमी, तीखा, शाकाहारी — अपना पसंदीदा स्वाद खोजें।',menuLink:'पूरा मेन्यू देखें',storyTitle:'ऐसा स्वाद जो <em>फर्क़ लाए।</em>',storyText:'अच्छी करी का कोई शॉर्टकट नहीं। मसाले, तंदूर और समय मिलकर यादगार स्वाद बनाते हैं।',visitTitle:'आइए एक <em>अच्छी शाम के लिए।</em>',visitLead:'रेस्तरां में, टेकअवे या डिलीवरी। हम वारसॉ में रूव्नोलेग्वा 2 पर हैं।',directions:'रास्ता देखें',addressLabel:'पता',hoursLabel:'समय',hours:'हर दिन · 11:00–22:00',footer:'वारसॉ व्लोही में भारतीय खाना',menuPageTitle:'आज क्या <em>ऑर्डर करेंगे?</em>',menuPageLead:'शुरू करने के लिए कुछ पसंदीदा व्यंजन। पूरा मेन्यू ऑर्डर पेज पर है।',visitPageTitle:'अच्छी करी <em>पास ही है।</em>',visitPageLead:'लंच, डिनर या घर जाते समय टेकअवे के लिए आइए।',selected:'हमारी पसंद'}
};
export const dishes = [
  {name:'Butter Chicken',description:['Kremowy sos pomidorowo-maślany, kurczak z tandoora i nerkowce.','Creamy tomato-butter sauce, tandoor chicken and cashews.','क्रीमी टमाटर-मक्खन सॉस, तंदूरी चिकन और काजू।']},
  {name:'Tikka Masala',description:['Pomidory, imbir, czosnek i wyrazista mieszanka indyjskich przypraw.','Tomatoes, ginger, garlic and a bold Indian spice blend.','टमाटर, अदरक, लहसुन और भरपूर भारतीय मसाले।']},
  {name:'Paneer Curry',description:['Indyjski paneer w rozgrzewającym sosie curry.','Indian paneer in a warming curry sauce.','गर्माहट भरी करी सॉस में भारतीय पनीर।']}
] as const;
export const langIndex=(lang:Lang)=>languages.indexOf(lang);
